# Generated by Django 5.2.5 on 2026-02-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('short_pitch', models.CharField(blank=True, max_length=200)),
                ('benefits', models.TextField(blank=True, help_text='Short paragraph: why this matters.')),
                ('whats_included', models.TextField(blank=True, help_text='Bullet-style text is okay.')),
                ('starting_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('cta_label', models.CharField(default='Request a Quote', max_length=60)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'title'],
            },
        ),
    ]
